name: Build & test

on:
  push:
    branches:
      - main
      - leading
      - issue/60
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    # Skip build if head commit contains 'skip ci'
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Check out
        uses: actions/checkout@v2
        
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Cache Gradle files for later Unit test
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
              
      # - name: Run Android Lint
      #   run: ./gradlew lintDebug

      # - name: Build with Gradle
        # run: ./gradlew assembleDebug

      # Cache build files for later deploy
      - name: Cache build files
        id: cache_build_id
        uses: actions/cache@v2
        with:
          path: app/build/outputs/apk/debug
          key: ${{ runner.os }}-${{ hashFiles('app/build.gradle') }}


  unit-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: build

    steps:
      - name: Check out
        uses: actions/checkout@v2
        
      - name: Cache Gradle files
        uses: actions/cache@v2
        with:
          path: |
            .gradlew
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Unit Test
        run: ./gradlew testDebug

      - name: Upload Reports
        uses: actions/upload-artifact@v2
        with:
          name: Test-Reports-API${{ matrix.api-level }}
          path: app/build/reports/tests/*
        if: always()

  # android-emulator-test:
  #   runs-on: macos-latest
  #   # needs: build

  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       api-level: [ 29, 30 ]

  #   steps:
  #     - name: checkout
  #       uses: actions/checkout@v2

  #     # setup JDK
  #     - name: set up JDK 11
  #       uses: actions/setup-java@v2
  #       with:
  #         distribution: 'zulu'
  #         java-version: '11'

  #     # https://docs.github.com/ja/actions/learn-github-actions/workflow-commands-for-github-actions#example
  #     - name: Set the target name to GITHUB_ENV 
  #       id: setup_target_name
  #       run: |
  #         target="default"
  #         if [ "${{ matrix.api-level }}" -ge "29" ]; then
  #           target="google_apis"
  #         fi
  #         echo "env_target=$target" >> $GITHUB_ENV

  #     - name: Run tests
  #       uses: reactivecircus/android-emulator-runner@v2
  #       with:
  #         api-level: ${{ matrix.api-level }}
  #         target: ${{ env.env_target }}
  #         arch: x86
  #         profile: Galaxy Nexus
  #         script: ./gradlew connectedCheck --stacktrace

  #     # Upload results as a artifact even if the test failed
  #     - name: Upload Reports
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: Test-Reports-API${{ matrix.api-level }}
  #         path: app/build/reports
  #       if: always()
  
  deploy:
    if: github.event_name == 'push'

    runs-on: ubuntu-latest
    # needs: [ build, test ]
    timeout-minutes: 30

    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Load build files from cache
        id: cache-build
        uses: actions/cache@v2
        with:
          path: app/build/outputs/apk/debug
          key: ${{ runner.os }}-${{ hashFiles('app/build.gradle') }}

      - name: Upload apk file
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: app/build/outputs/apk/debug/app-debug.apk
          retention-days: 3
